# Generated by Django 4.1.2 on 2022-11-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStyleLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image_style_life/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мой стиль',
                'verbose_name_plural': 'Мой стиль',
            },
        ),
        migrations.CreateModel(
            name='MyLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Моя жизнь',
                'verbose_name_plural': 'Моя жизнь',
            },
        ),
    ]
