# Generated by Django 4.1.2 on 2022-10-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='image_mini/', verbose_name='Мини изображение')),
            ],
            options={
                'verbose_name': 'Изображение к посту',
                'verbose_name_plural': 'Изображения к посту',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='mini_image',
        ),
        migrations.AddField(
            model_name='post',
            name='mini_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.imagespost', verbose_name='Изображение к посту'),
        ),
    ]
