# Generated by Django 4.1.2 on 2022-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_mini_image_alter_post_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(default=0, related_name='post_views', to='blog.ip', verbose_name='Просмотры'),
        ),
    ]
