# Generated by Django 4.1.2 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
