# Generated by Django 4.1.2 on 2022-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Окрас',
                'verbose_name_plural': 'Краски',
            },
        ),
    ]
