# Generated by Django 4.1.2 on 2022-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Главное изображение продукта'),
        ),
        migrations.AddField(
            model_name='specification',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='quality_checking',
            field=models.CharField(max_length=150, verbose_name='Проверка качества'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='when_packeting',
            field=models.CharField(max_length=150, verbose_name='При упаковке'),
        ),
    ]
