# Generated by Django 4.1.2 on 2022-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_product', models.ManyToManyField(to='shop.product', verbose_name='Товары недели')),
            ],
            options={
                'verbose_name': 'Товар этой недели',
                'verbose_name_plural': 'Товары этой недели',
            },
        ),
    ]
