# Generated by Django 4.1.2 on 2022-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_main_image_specification_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(related_name='product', to='shop.specification', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(related_name='product', to='shop.brand', verbose_name='Бренд'),
        ),
    ]
