# Generated by Django 4.1.2 on 2022-11-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_weekproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekproduct',
            name='week_product',
        ),
        migrations.AddField(
            model_name='weekproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение продукта'),
        ),
        migrations.AddField(
            model_name='weekproduct',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='weekproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='weekproduct',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
    ]
