# Generated by Django 4.1.2 on 2022-11-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_weekproduct_week_product_weekproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.product', verbose_name='Продукт'),
        ),
    ]
