# Generated by Django 4.1.2 on 2022-10-21 16:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('company_name', models.CharField(max_length=150, verbose_name='Компания')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Данные заказчика',
                'verbose_name_plural': 'Данные заказчика',
            },
        ),
    ]
