# Generated by Django 4.1.2 on 2022-10-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitemlist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Примечания к заказу'),
        ),
        migrations.AlterField(
            model_name='orderitemlist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.order', verbose_name='Заказ'),
        ),
    ]
