# Generated by Django 4.1.2 on 2022-10-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Данные заказчика', 'verbose_name_plural': 'Данные заказчика'},
        ),
        migrations.AlterModelOptions(
            name='orderitemlist',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
    ]
